name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyterlab
  - jupyter=1.0
  - seaborn
  - pandas
  - pip
  - pandas-profiling=3.1
  - pyarrow
  - wandb
  - pip:
    - nbconvert==5.6.1