name: download_file
channels:
  - conda-forge
  - defaults
  - conda-forge/label/broke
dependencies:
  - pip=23.1
  - requests=2.31
  - mlflow=2.3
  - scikit-learn=1.2
  - wandb=0.15
  - pip:
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
