name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
  - conda-forge/label/broke
dependencies:
  - python=3.8
  - nbformat=5.4
  - mlflow=2.3
  - ipython=7.21
  - notebook=6.2
  - jupyterlab=3.0
  - cookiecutter=1.7
  - hydra-core=1.0
  - matplotlib=3.6
  - pandas=2.0
  - git=2.41
  - pip=23.1
  - wandb=0.15
