name: basic_cleaning
channels:
  - conda-forge
  - defaults
  - conda-forge/label/broke
dependencies:
  - pandas=2.1
  - pip=23.1
  - mlflow=2.3
  - scikit-learn=1.2
  - matplotlib=3.2.2
  - pillow=8.1.2
  - wandb==0.15
