name: basic_cleaning
channels:
  - conda-forge
  - defaults
  - conda-forge/label/broke
dependencies:
  - pandas=2.0
  - pip=23.1
  - mlflow=2.3
  - scikit-learn=0.24.1
  - matplotlib=3.7
  - pillow=8.1.2
  - wandb==0.15
